

server:
  port: 9111
  servlet:
    context-path: /admin

spring:
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp160f3y7w85m00o31o.mysql.rds.aliyuncs.com:3306/admin?useSSL=false
    username: test_1
    password: 'zxcvbnm@123'
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 100
      minimum-idle: 15
      pool-name: HikariConnectionPool
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.java.admin.entity


#mapper:
#  mappers:
#    - com.zoomlion.framework.base.mapper.BaseMapper
#  not-empty: false
#  identity: MYSQL
